"""empty message

Revision ID: 10aa77e4e8de
Revises: 42dd247f7317
Create Date: 2019-03-10 12:03:57.117069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10aa77e4e8de'
down_revision = '42dd247f7317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('order_refference', sa.Integer(), nullable=True))
    op.drop_column('payment', 'oreder_refference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('oreder_refference', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('payment', 'order_refference')
    # ### end Alembic commands ###
