"""empty message

Revision ID: 2460a1959f4c
Revises: 
Create Date: 2019-03-03 16:23:17.763214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2460a1959f4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('alamat', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=200), nullable=True))
    op.drop_column('user', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('user', 'email')
    op.drop_column('user', 'alamat')
    # ### end Alembic commands ###
