"""empty message

Revision ID: 42dd247f7317
Revises: 2460a1959f4c
Create Date: 2019-03-10 11:42:14.466719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42dd247f7317'
down_revision = '2460a1959f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('bukti_transfer', sa.String(length=200), nullable=True))
    op.add_column('payment', sa.Column('date_time', sa.String(length=200), nullable=True))
    op.add_column('payment', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'status')
    op.drop_column('payment', 'date_time')
    op.drop_column('payment', 'bukti_transfer')
    # ### end Alembic commands ###
